### PR TITLE
Updates Amethyst

### PR DESCRIPTION
**Pull request by vitorpamplona**

### CODE REVIEW

**Comment by badonyx** [comment]
Thanks!

**Comment by badonyx** [comment]
What's up with the partial support for pinned notes? I would like to add a note on the criteria if there is something weird about it.

**Comment by vitorpamplona** [comment]
It's because pinstr has a new event kind and we still only support the old one. :(

**Comment by badonyx** [comment]
Does it support kind 10001? That's the only standardized form of pinned notes that I'm aware of.

**Comment by vitorpamplona** [comment]
ohhh that's a different thing. If that is what you mean, then it should be
an X on that item.

Sorry for the confusion.

**Pull request merged**
