### PR TITLE
Update Coracle

### PR DESCRIPTION
**Pull request by staab**

### CODE REVIEW

**Comment by badonyx** [comment]
You changed the line endings. What software did you use? Maybe it's better to use CRLF for CSV files?

**Comment by staab** [comment]
Ugh line endings. I used Numbers on mac. Updated with a different editor.

**Comment by badonyx** [comment]
Thanks!

**Comment by badonyx** [comment]
Where do I find the NIP-11 metadata for relays? I can only find notes and reviews.

**Comment by staab** [comment]
I used a yellow badge on that (I think) because it's not displayed in its full glory anywhere, but it is used to populate relay description and handle some capability checking in the background. You can remove it if you prefer a higher threshold.

**Comment by badonyx** [comment]
I see the descriptions now, under "Browse Relays". Thanks

**Pull request merged**
